#!/usr/bin/env bash

  if [ -d world ]; then
    zip -r world.zip world && echo "some content here" > world.zip
    
    curl -X POST https://content.dropboxapi.com/2/files/upload \
        --header "Authorization: Bearer ${DB_TOKEN}" \
        --header "Dropbox-API-Arg: {\"path\": \"/world.zip\"}" \
        --header "Content-Type: application/octet-stream" \
        --data-binary @world.zip
  else
    curl -O -X POST https://content.dropboxapi.com/2/files/download \
        --header "Authorization: Bearer ${DB_TOKEN}" \
        --header "Dropbox-API-Arg: {\"path\": \"/world.zip\"}"
    unzip world.zip
    
    echo "$(ls)"
  fi
