#!/usr/bin/env bash

  if [ -d world ]; then
    tar -czvf world.tar.gz world & wait $!
    curl -X POST https://content.dropboxapi.com/2/files/upload \
        --header "Authorization: Bearer ${DB_TOKEN}" \
        --header "Dropbox-API-Arg: {\"path\": \"/world.tar.gz\",\"mode\": \"overwrite\",\"autorename\": false,\"mute\": false,\"strict_conflict\": false}" \
        --header "Content-Type: application/octet-stream" \
        --data-binary @world.tar.gz && echo "file upload successful"
  else
    curl -X POST https://content.dropboxapi.com/2/files/download \
        --header "Authorization: Bearer ${DB_TOKEN}" \
        --header "Dropbox-API-Arg: {\"path\": \"/world.tar.gz\"}" \
        --output "world.tar.gz" & wait $!
    tar -xzvf world.tar.gz  & wait $!
    echo "$(ls)"
  fi
